name: Build llamafile

on:
    workflow_dispatch:
        inputs:
            model_url:
                description: "URL to the model to be used"
                required: true


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                repository: "Mozilla-Ocho/llamafile"
                ref: "main"

            - name: llamafile gotchas error
              run: |
                sudo wget -O /usr/bin/ape https://cosmo.zip/pub/cosmos/bin/ape-$(uname -m).elf
                sudo chmod +x /usr/bin/ape
                sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
                sudo sh -c "echo ':APE-jart:M::jartsr::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

            - name: Install GCC and Make
              run: sudo apt-get install make gcc g++ -y

            - name: Prepare build
              run: |
                make -j$(nproc)
                sudo make install PREFIX=/usr/local

            - name: Find model name
              id: model_name
              run: |
                modeln=${{ github.event.inputs.model_url }} | grep -o '[^/]*$' | sed 's/?download=true//'
                echo "model=$modeln" >> $GITHUB_OUTPUT

            - name: Download model
              run: |
                wget -O ${{ steps.model_name.outputs.model }} ${{ github.event.inputs.model_url }}

            - name: Create .args
              run: |
                echo "-m" > .args
                echo "${{ steps.model_name.outputs.model }}" >> .args
                echo "--host" >> .args
                echo "0.0.0.0" >> .args
                echo "..." >> .args

            - name: Prepare llama-server
              run: |
                # remove extension from model name
                file_ext_removed_model_name=$(echo ${{ steps.model_name.outputs.model }} | sed 's/\.[^.]*$//')
                cp /usr/local/bin/llamafile-server "$file_ext_removed_model_name".llamafile
                zipalign -j0 "$file_ext_removed_model_name".llamafile ${{ steps.model_name.outputs.model }} .args

            - name: Upload llamafile
              uses: actions/upload-artifact@v2
              with:
                name: ${{ steps.model_name.outputs.model }}.llamafile
                path: "*.llamafile"


            

            

            
